### PR TITLE
Fix #42, Add no_std support

### LINKED ISSUE #42: Features not behaving additively
I ran into issues using a library that had this library at two places in the dependency graph.

as noted for the example below when the Unicode feature is enabled it changes the observed behavior of seemly non-Unicode strings

I would expect the bellow test to pass and have the same behavior both with:
cargo test
cargo test --features unicode (outputs Entity.allay.ambientWithItem instead of the behavior bellow)
```
t!(test9: "entity.allay.ambient_with_item" => "EntityAllayAmbientWithItem");
```

### PR DESCRIPTION
**Pull request by rj00a**
- Close #42, #41. Removes `unicode` feature and `unicode-segmentation` dependency. `char::is_alphanumeric` is now used to determine word boundaries. This change also lets us remove the special case for the underscore character.
- Added no_std support. I didn't have a use for this personally, but maybe someone will.
- Bumped version to `0.5.0` and updated changelog. The crate is ready to be published.

### CODE REVIEW

**Comment by rj00a** [comment]
Hmm, was `extern crate alloc` not a thing in Rust 1.32? I'm not super familiar with how `no_std` works.

**Comment by rj00a** [comment]
This fixes #41. The previous impl used `is_ascii_alphanumeric` which completely threw away non-ascii characters.

File: src/shouty_snake.rs [hunk 1]
```diff
@@ -20,7 +22,7 @@ pub trait ToShoutySnakeCase: ToOwned {
     fn to_shouty_snake_case(&self) -> Self::Owned;
 }
 
-/// Oh heck, ToShoutySnekCase is an alias for ToShoutySnakeCase. See
+/// Oh heck, ToShoutySnekCase is an alias for [`ToShoutySnakeCase`]. See
```
Comment (jplatte) [inline src/shouty_snake.rs:25]:
```suggestion
/// Oh heck, `ToShoutySnekCase` is an alias for [`ToShoutySnakeCase`]. See
```

File: src/snake.rs [hunk 2]
```diff
@@ -19,7 +23,7 @@ pub trait ToSnakeCase: ToOwned {
     fn to_snake_case(&self) -> Self::Owned;
 }
 
-/// Oh heck, SnekCase is an alias for ToSnakeCase. See ToSnakeCase for
+/// Oh heck, SnekCase is an alias for [`ToSnakeCase`]. See ToSnakeCase for
```
Comment (jplatte) [inline src/snake.rs:26]:
```suggestion
/// Oh heck, `SnekCase` is an alias for [`ToSnakeCase`]. See ToSnakeCase for
```

File: src/shouty_snake.rs (hunk 1 above)
Comment (jplatte) [reply src/shouty_snake.rs:25]: Should ideally be a separate PR, but I don't mind that much.

File: src/upper_camel.rs [hunk 3]
```diff
@@ -26,7 +31,7 @@ impl ToUpperCamelCase for str {
     }
 }
 
-/// ToPascalCase is an alias for ToUpperCamelCase. See ToUpperCamelCase for more
+/// ToPascalCase is an alias for [`ToUpperCamelCase`]. See ToUpperCamelCase for more
```
Comment (jplatte) [inline src/upper_camel.rs:34]:
```suggestion
/// `ToPascalCase` is an alias for [`ToUpperCamelCase`]. See ToUpperCamelCase for more
```

**Comment by jplatte** [comment]
Anyways, thanks! 💚

**Comment by rj00a** [comment]
Before you go, I should also mention that I considered using XID_Start+XID_Continue as an alternative to `char::is_alphanumeric`. That would bring some parity with Rust identifiers for what it's worth.

The character sets don't overlap completely.

<details>
  <summary>Here's all the chars that are alphanumeric but not XID_Continue</summary>
  
² ³ ¹ ¼ ½ ¾ ͺ ৴ ৵ ৶ ৷ ৸ ৹ ୲ ୳ ୴ ୵ ୶ ୷ ௰ ௱ ௲ ౸ ౹ ౺ ౻ ౼ ౽ ౾ ൘ ൙ ൚ ൛ ൜ ൝ ൞ ൰ ൱ ൲ ൳ ൴ ൵ ൶ ൷ ൸ ༪ ༫ ༬ ༭ ༮ ༯ ༰ ༱ ༲ ༳ ፲ ፳ ፴ ፵ ፶ ፷ ፸ ፹ ፺ ፻ ፼ ៰ ៱ ៲ ៳ ៴ ៵ ៶ ៷ ៸ ៹ ⁰ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹ ₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉ ⅐ ⅑ ⅒ ⅓ ⅔ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞ ⅟ ↉ ① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ ⑩ ⑪ ⑫ ⑬ ⑭ ⑮ ⑯ ⑰ ⑱ ⑲ ⑳ ⑴ ⑵ ⑶ ⑷ ⑸ ⑹ ⑺ ⑻ ⑼ ⑽ ⑾ ⑿ ⒀ ⒁ ⒂ ⒃ ⒄ ⒅ ⒆ ⒇ ⒈ ⒉ ⒊ ⒋ ⒌ ⒍ ⒎ ⒏ ⒐ ⒑ ⒒ ⒓ ⒔ ⒕ ⒖ ⒗ ⒘ ⒙ ⒚ ⒛ Ⓐ Ⓑ Ⓒ Ⓓ Ⓔ Ⓕ Ⓖ Ⓗ Ⓘ Ⓙ Ⓚ Ⓛ Ⓜ Ⓝ Ⓞ Ⓟ Ⓠ Ⓡ Ⓢ Ⓣ Ⓤ Ⓥ Ⓦ Ⓧ Ⓨ Ⓩ ⓐ ⓑ ⓒ ⓓ ⓔ ⓕ ⓖ ⓗ ⓘ ⓙ ⓚ ⓛ ⓜ ⓝ ⓞ ⓟ ⓠ ⓡ ⓢ ⓣ ⓤ ⓥ ⓦ ⓧ ⓨ ⓩ ⓪ ⓫ ⓬ ⓭ ⓮ ⓯ ⓰ ⓱ ⓲ ⓳ ⓴ ⓵ ⓶ ⓷ ⓸ ⓹ ⓺ ⓻ ⓼ ⓽ ⓾ ⓿ ❶ ❷ ❸ ❹ ❺ ❻ ❼ ❽ ❾ ❿ ➀ ➁ ➂ ➃ ➄ ➅ ➆ ➇ ➈ ➉ ➊ ➋ ➌ ➍ ➎ ➏ ➐ ➑ ➒ ➓ ⳽ ⸯ ㆒ ㆓ ㆔ ㆕ ㈠ ㈡ ㈢ ㈣ ㈤ ㈥ ㈦ ㈧ ㈨ ㈩ ㉈ ㉉ ㉊ ㉋ ㉌ ㉍ ㉎ ㉏ ㉑ ㉒ ㉓ ㉔ ㉕ ㉖ ㉗ ㉘ ㉙ ㉚ ㉛ ㉜ ㉝ ㉞ ㉟ ㊀ ㊁ ㊂ ㊃ ㊄ ㊅ ㊆ ㊇ ㊈ ㊉ ㊱ ㊲ ㊳ ㊴ ㊵ ㊶ ㊷ ㊸ ㊹ ㊺ ㊻ ㊼ ㊽ ㊾ ㊿ ꠰ ꠱ ꠲ ꠳ ꠴ ꠵ ﱞ ﱟ ﱠ ﱡ ﱢ ﱣ ﷺ ﷻ ﹰ ﹲ ﹴ ﹶ ﹸ ﹺ ﹼ ﹾ 𐄇 𐄈 𐄉 𐄊 𐄋 𐄌 𐄍 𐄎 𐄏 𐄐 𐄑 𐄒 𐄓 𐄔 𐄕 𐄖 𐄗 𐄘 𐄙 𐄚 𐄛 𐄜 𐄝 𐄞 𐄟 𐄠 𐄡 𐄢 𐄣 𐄤 𐄥 𐄦 𐄧 𐄨 𐄩 𐄪 𐄫 𐄬 𐄭 𐄮 𐄯 𐄰 𐄱 𐄲 𐄳 𐅵 𐅶 𐅷 𐅸 𐆊 𐆋 𐋡 𐋢 𐋣 𐋤 𐋥 𐋦 𐋧 𐋨 𐋩 𐋪 𐋫 𐋬 𐋭 𐋮 𐋯 𐋰 𐋱 𐋲 𐋳 𐋴 𐋵 𐋶 𐋷 𐋸 𐋹 𐋺 𐋻 𐌠 𐌡 𐌢 𐌣 𐡘 𐡙 𐡚 𐡛 𐡜 𐡝 𐡞 𐡟 𐡹 𐡺 𐡻 𐡼 𐡽 𐡾 𐡿 𐢧 𐢨 𐢩 𐢪 𐢫 𐢬 𐢭 𐢮 𐢯 𐣻 𐣼 𐣽 𐣾 𐣿 𐤖 𐤗 𐤘 𐤙 𐤚 𐤛 𐦼 𐦽 𐧀 𐧁 𐧂 𐧃 𐧄 𐧅 𐧆 𐧇 𐧈 𐧉 𐧊 𐧋 𐧌 𐧍 𐧎 𐧏 𐧒 𐧓 𐧔 𐧕 𐧖 𐧗 𐧘 𐧙 𐧚 𐧛 𐧜 𐧝 𐧞 𐧟 𐧠 𐧡 𐧢 𐧣 𐧤 𐧥 𐧦 𐧧 𐧨 𐧩 𐧪 𐧫 𐧬 𐧭 𐧮 𐧯 𐧰 𐧱 𐧲 𐧳 𐧴 𐧵 𐧶 𐧷 𐧸 𐧹 𐧺 𐧻 𐧼 𐧽 𐧾 𐧿 𐩀 𐩁 𐩂 𐩃 𐩄 𐩅 𐩆 𐩇 𐩈 𐩽 𐩾 𐪝 𐪞 𐪟 𐫫 𐫬 𐫭 𐫮 𐫯 𐭘 𐭙 𐭚 𐭛 𐭜 𐭝 𐭞 𐭟 𐭸 𐭹 𐭺 𐭻 𐭼 𐭽 𐭾 𐭿 𐮩 𐮪 𐮫 𐮬 𐮭 𐮮 𐮯 𐳺 𐳻 𐳼 𐳽 𐳾 𐳿 𐹠 𐹡 𐹢 𐹣 𐹤 𐹥 𐹦 𐹧 𐹨 𐹩 𐹪 𐹫 𐹬 𐹭 𐹮 𐹯 𐹰 𐹱 𐹲 𐹳 𐹴 𐹵 𐹶 𐹷 𐹸 𐹹 𐹺 𐹻 𐹼 𐹽 𐹾 𐼝 𐼞 𐼟 𐼠 𐼡 𐼢 𐼣 𐼤 𐼥 𐼦 𐽑 𐽒 𐽓 𐽔 𐿅 𐿆 𐿇 𐿈 𐿉 𐿊 𐿋 𑁒 𑁓 𑁔 𑁕 𑁖 𑁗 𑁘 𑁙 𑁚 𑁛 𑁜 𑁝 𑁞 𑁟 𑁠 𑁡 𑁢 𑁣 𑁤 𑁥 𑇡 𑇢 𑇣 𑇤 𑇥 𑇦 𑇧 𑇨 𑇩 𑇪 𑇫 𑇬 𑇭 𑇮 𑇯 𑇰 𑇱 𑇲 𑇳 𑇴 𑜺 𑜻 𑣪 𑣫 𑣬 𑣭 𑣮 𑣯 𑣰 𑣱 𑣲 𑱚 𑱛 𑱜 𑱝 𑱞 𑱟 𑱠 𑱡 𑱢 𑱣 𑱤 𑱥 𑱦 𑱧 𑱨 𑱩 𑱪 𑱫 𑱬 𑿀 𑿁 𑿂 𑿃 𑿄 𑿅 𑿆 𑿇 𑿈 𑿉 𑿊 𑿋 𑿌 𑿍 𑿎 𑿏 𑿐 𑿑 𑿒 𑿓 𑿔 𖭛 𖭜 𖭝 𖭞 𖭟 𖭠 𖭡 𖺀 𖺁 𖺂 𖺃 𖺄 𖺅 𖺆 𖺇 𖺈 𖺉 𖺊 𖺋 𖺌 𖺍 𖺎 𖺏 𖺐 𖺑 𖺒 𖺓 𖺔 𖺕 𖺖 𝋀 𝋁 𝋂 𝋃 𝋄 𝋅 𝋆 𝋇 𝋈 𝋉 𝋊 𝋋 𝋌 𝋍 𝋎 𝋏 𝋐 𝋑 𝋒 𝋓 𝋠 𝋡 𝋢 𝋣 𝋤 𝋥 𝋦 𝋧 𝋨 𝋩 𝋪 𝋫 𝋬 𝋭 𝋮 𝋯 𝋰 𝋱 𝋲 𝋳 𝍠 𝍡 𝍢 𝍣 𝍤 𝍥 𝍦 𝍧 𝍨 𝍩 𝍪 𝍫 𝍬 𝍭 𝍮 𝍯 𝍰 𝍱 𝍲 𝍳 𝍴 𝍵 𝍶 𝍷 𝍸 𞣇 𞣈 𞣉 𞣊 𞣋 𞣌 𞣍 𞣎 𞣏 𞱱 𞱲 𞱳 𞱴 𞱵 𞱶 𞱷 𞱸 𞱹 𞱺 𞱻 𞱼 𞱽 𞱾 𞱿 𞲀 𞲁 𞲂 𞲃 𞲄 𞲅 𞲆 𞲇 𞲈 𞲉 𞲊 𞲋 𞲌 𞲍 𞲎 𞲏 𞲐 𞲑 𞲒 𞲓 𞲔 𞲕 𞲖 𞲗 𞲘 𞲙 𞲚 𞲛 𞲜 𞲝 𞲞 𞲟 𞲠 𞲡 𞲢 𞲣 𞲤 𞲥 𞲦 𞲧 𞲨 𞲩 𞲪 𞲫 𞲭 𞲮 𞲯 𞲱 𞲲 𞲳 𞲴 𞴁 𞴂 𞴃 𞴄 𞴅 𞴆 𞴇 𞴈 𞴉 𞴊 𞴋 𞴌 𞴍 𞴎 𞴏 𞴐 𞴑 𞴒 𞴓 𞴔 𞴕 𞴖 𞴗 𞴘 𞴙 𞴚 𞴛 𞴜 𞴝 𞴞 𞴟 𞴠 𞴡 𞴢 𞴣 𞴤 𞴥 𞴦 𞴧 𞴨 𞴩 𞴪 𞴫 𞴬 𞴭 𞴯 𞴰 𞴱 𞴲 𞴳 𞴴 𞴵 𞴶 𞴷 𞴸 𞴹 𞴺 𞴻 𞴼 𞴽 🄀 🄁 🄂 🄃 🄄 🄅 🄆 🄇 🄈 🄉 🄊 🄋 🄌 🄰 🄱 🄲 🄳 🄴 🄵 🄶 🄷 🄸 🄹 🄺 🄻 🄼 🄽 🄾 🄿 🅀 🅁 🅂 🅃 🅄 🅅 🅆 🅇 🅈 🅉 🅐 🅑 🅒 🅓 🅔 🅕 🅖 🅗 🅘 🅙 🅚 🅛 🅜 🅝 🅞 🅟 🅠 🅡 🅢 🅣 🅤 🅥 🅦 🅧 🅨 🅩 🅰 🅱 🅲 🅳 🅴 🅵 🅶 🅷 🅸 🅹 🅺 🅻 🅼 🅽 🅾 🅿 🆀 🆁 🆂 🆃 🆄 🆅 🆆 🆇 🆈 🆉
</details>

<details>
<summary>And here are all the chars that are XID_Continue but not alphanumeric</summary>

_ · ̀ ́ ̂ ̃ ̄ ̅ ̆ ̇ ̈ ̉ ̊ ̋ ̌ ̍ ̎ ̏ ̐ ̑ ̒ ̓ ̔ ̕ ̖ ̗ ̘ ̙ ̚ ̛ ̜ ̝ ̞ ̟ ̠ ̡ ̢ ̣ ̤ ̥ ̦ ̧ ̨ ̩ ̪ ̫ ̬ ̭ ̮ ̯ ̰ ̱ ̲ ̳ ̴ ̵ ̶ ̷ ̸ ̹ ̺ ̻ ̼ ̽ ̾ ̿ ̀ ́ ͂ ̓ ̈́ ͆ ͇ ͈ ͉ ͊ ͋ ͌ ͍ ͎ ͏ ͐ ͑ ͒ ͓ ͔ ͕ ͖ ͗ ͘ ͙ ͚ ͛ ͜ ͝ ͞ ͟ ͠ ͡ ͢ ͣ ͤ ͥ ͦ ͧ ͨ ͩ ͪ ͫ ͬ ͭ ͮ ͯ · ҃ ҄ ҅ ҆ ҇ ֑ ֒ ֓ ֔ ֕ ֖ ֗ ֘ ֙ ֚ ֛ ֜ ֝ ֞ ֟ ֠ ֡ ֢ ֣ ֤ ֥ ֦ ֧ ֨ ֩ ֪ ֫ ֬ ֭ ֮ ֯ ٘ ۟ ۠ ۪ ۫ ۬ ݀ ݁ ݂ ݃ ݄ ݅ ݆ ݇ ݈ ݉ ݊ ߫ ߬ ߭ ߮ ߯ ߰ ߱ ߲ ߳ ߽ ࠘ ࠙ ࠭ ࡙ ࡚ ࡛ ࢘ ࢙ ࢚ ࢛ ࢜ ࢝ ࢞ ࢟ ࣊ ࣋ ࣌ ࣍ ࣎ ࣏ ࣐ ࣑ ࣒ ࣓ ࣠ ࣡ ࣪ ࣫ ࣬ ࣭ ࣮ ࣯ ़ ् ॑ ॒ ॓ ॔ ় ্ ৾ ਼ ੍ ઼ ્ ૽ ૾ ૿ ଼ ୍ ୕ ் ఼ ్ ಼ ್ ഻ ഼ ് ් ็ ่ ้ ๊ ๋ ์ ๎ ຺ ່ ້ ໊ ໋ ໌ ໎ ༘ ༙ ༵ ༷ ༹ ༾ ༿ ྄ ྆ ྇ ࿆ ့ ္ ် ፝ ፞ ፟ ᜔ ᜕ ᜴ ឴ ឵ ៉ ៊ ់ ៌ ៍ ៎ ៏ ័ ៑ ្ ៓ ៝ ᠋ ᠌ ᠍ ᠏ ᤹ ᤺ ᤻ ᩠ ᩵ ᩶ ᩷ ᩸ ᩹ ᩺ ᩻ ᩼ ᩿ ᪰ ᪱ ᪲ ᪳ ᪴ ᪵ ᪶ ᪷ ᪸ ᪹ ᪺ ᪻ ᪼ ᪽ ᫁ ᫂ ᫃ ᫄ ᫅ ᫆ ᫇ ᫈ ᫉ ᫊ ᫋ ᬴ ᭄ ᭫ ᭬ ᭭ ᭮ ᭯ ᭰ ᭱ ᭲ ᭳ ᮪ ᮫ ᯦ ᯲ ᯳ ᰷ ᳐ ᳑ ᳒ ᳔ ᳕ ᳖ ᳗ ᳘ ᳙ ᳚ ᳛ ᳜ ᳝ ᳞ ᳟ ᳠ ᳡ ᳢ ᳣ ᳤ ᳥ ᳦ ᳧ ᳨ ᳭ ᳴ ᳷ ᳸ ᳹ ᷀ ᷁ ᷂ ᷃ ᷄ ᷅ ᷆ ᷇ ᷈ ᷉ ᷊ ᷋ ᷌ ᷍ ᷎ ᷏ ᷐ ᷑ ᷒ ᷓ ᷔ ᷕ ᷖ ᷗ ᷘ ᷙ ᷚ ᷛ ᷜ ᷝ ᷞ ᷟ ᷠ ᷡ ᷢ ᷣ ᷤ ᷥ ᷦ ᷵ ᷶ ᷷ ᷸ ᷹ ᷺ ᷻ ᷼ ᷽ ᷾ ᷿ ‿ ⁀ ⁔ ⃐ ⃑ ⃒ ⃓ ⃔ ⃕ ⃖ ⃗ ⃘ ⃙ ⃚ ⃛ ⃜ ⃡ ⃥ ⃦ ⃧ ⃨ ⃩ ⃪ ⃫ ⃬ ⃭ ⃮ ⃯ ⃰ ℘ ℮ ⳯ ⳰ ⳱ ⵿ 〪 〫 〬 〭 〮 〯 ゙ ゚ ꙯ ꙼ ꙽ ꛰ ꛱ ꠆ ꠬ ꣄ ꣠ ꣡ ꣢ ꣣ ꣤ ꣥ ꣦ ꣧ ꣨ ꣩ ꣪ ꣫ ꣬ ꣭ ꣮ ꣯ ꣰ ꣱ ꤫ ꤬ ꤭ ꥓ ꦳ ꧀ ꪿ ꫁ ꫶ ꯬ ꯭ ︀ ︁ ︂ ︃ ︄ ︅ ︆ ︇ ︈ ︉ ︊ ︋ ︌ ︍ ︎ ️ ︠ ︡ ︢ ︣ ︤ ︥ ︦ ︧ ︨ ︩ ︪ ︫ ︬ ︭ ︮ ︯ ︳ ︴ ﹍ ﹎ ﹏ ＿ 𐇽 𐋠 𐨸 𐨹 𐨺 𐨿 𐫥 𐫦 𐻽 𐻾 𐻿 𐽆 𐽇 𐽈 𐽉 𐽊 𐽋 𐽌 𐽍 𐽎 𐽏 𐽐 𐾂 𐾃 𐾄 𐾅 𑁆 𑁰 𑁿 𑂹 𑂺 𑄳 𑄴 𑅳 𑇀 𑇉 𑇊 𑇋 𑇌 𑈵 𑈶 𑋩 𑋪 𑌻 𑌼 𑍍 𑍦 𑍧 𑍨 𑍩 𑍪 𑍫 𑍬 𑍰 𑍱 𑍲 𑍳 𑍴 𑑂 𑑆 𑑞 𑓂 𑓃 𑖿 𑗀 𑘿 𑚶 𑚷 𑜫 𑠹 𑠺 𑤽 𑤾 𑥃 𑧠 𑨳 𑨴 𑩇 𑪘 𑪙 𑰿 𑵂 𑵄 𑵅 𑶗 𑽁 𑽂 𓑀 𓑇 𓑈 𓑉 𓑊 𓑋 𓑌 𓑍 𓑎 𓑏 𓑐 𓑑 𓑒 𓑓 𓑔 𓑕 𖫰 𖫱 𖫲 𖫳 𖫴 𖬰 𖬱 𖬲 𖬳 𖬴 𖬵 𖬶 𖿤 𛲝 𜼀 𜼁 𜼂 𜼃 𜼄 𜼅 𜼆 𜼇 𜼈 𜼉 𜼊 𜼋 𜼌 𜼍 𜼎 𜼏 𜼐 𜼑 𜼒 𜼓 𜼔 𜼕 𜼖 𜼗 𜼘 𜼙 𜼚 𜼛 𜼜 𜼝 𜼞 𜼟 𜼠 𜼡 𜼢 𜼣 𜼤 𜼥 𜼦 𜼧 𜼨 𜼩 𜼪 𜼫 𜼬 𜼭 𜼰 𜼱 𜼲 𜼳 𜼴 𜼵 𜼶 𜼷 𜼸 𜼹 𜼺 𜼻 𜼼 𜼽 𜼾 𜼿 𜽀 𜽁 𜽂 𜽃 𜽄 𜽅 𜽆 𝅥 𝅦 𝅧 𝅨 𝅩 𝅭 𝅮 𝅯 𝅰 𝅱 𝅲 𝅻 𝅼 𝅽 𝅾 𝅿 𝆀 𝆁 𝆂 𝆅 𝆆 𝆇 𝆈 𝆉 𝆊 𝆋 𝆪 𝆫 𝆬 𝆭 𝉂 𝉃 𝉄 𝨀 𝨁 𝨂 𝨃 𝨄 𝨅 𝨆 𝨇 𝨈 𝨉 𝨊 𝨋 𝨌 𝨍 𝨎 𝨏 𝨐 𝨑 𝨒 𝨓 𝨔 𝨕 𝨖 𝨗 𝨘 𝨙 𝨚 𝨛 𝨜 𝨝 𝨞 𝨟 𝨠 𝨡 𝨢 𝨣 𝨤 𝨥 𝨦 𝨧 𝨨 𝨩 𝨪 𝨫 𝨬 𝨭 𝨮 𝨯 𝨰 𝨱 𝨲 𝨳 𝨴 𝨵 𝨶 𝨻 𝨼 𝨽 𝨾 𝨿 𝩀 𝩁 𝩂 𝩃 𝩄 𝩅 𝩆 𝩇 𝩈 𝩉 𝩊 𝩋 𝩌 𝩍 𝩎 𝩏 𝩐 𝩑 𝩒 𝩓 𝩔 𝩕 𝩖 𝩗 𝩘 𝩙 𝩚 𝩛 𝩜 𝩝 𝩞 𝩟 𝩠 𝩡 𝩢 𝩣 𝩤 𝩥 𝩦 𝩧 𝩨 𝩩 𝩪 𝩫 𝩬 𝩵 𝪄 𝪛 𝪜 𝪝 𝪞 𝪟 𝪡 𝪢 𝪣 𝪤 𝪥 𝪦 𝪧 𝪨 𝪩 𝪪 𝪫 𝪬 𝪭 𝪮 𝪯 𞄰 𞄱 𞄲 𞄳 𞄴 𞄵 𞄶 𞊮 𞋬 𞋭 𞋮 𞋯 𞓬 𞓭 𞓮 𞓯 𞣐 𞣑 𞣒 𞣓 𞣔 𞣕 𞣖 𞥄 𞥅 𞥆 𞥈 𞥉 𞥊 󠄀 󠄁 󠄂 󠄃 󠄄 󠄅 󠄆 󠄇 󠄈 󠄉 󠄊 󠄋 󠄌 󠄍 󠄎 󠄏 󠄐 󠄑 󠄒 󠄓 󠄔 󠄕 󠄖 󠄗 󠄘 󠄙 󠄚 󠄛 󠄜 󠄝 󠄞 󠄟 󠄠 󠄡 󠄢 󠄣 󠄤 󠄥 󠄦 󠄧 󠄨 󠄩 󠄪 󠄫 󠄬 󠄭 󠄮 󠄯 󠄰 󠄱 󠄲 󠄳 󠄴 󠄵 󠄶 󠄷 󠄸 󠄹 󠄺 󠄻 󠄼 󠄽 󠄾 󠄿 󠅀 󠅁 󠅂 󠅃 󠅄 󠅅 󠅆 󠅇 󠅈 󠅉 󠅊 󠅋 󠅌 󠅍 󠅎 󠅏 󠅐 󠅑 󠅒 󠅓 󠅔 󠅕 󠅖 󠅗 󠅘 󠅙 󠅚 󠅛 󠅜 󠅝 󠅞 󠅟 󠅠 󠅡 󠅢 󠅣 󠅤 󠅥 󠅦 󠅧 󠅨 󠅩 󠅪 󠅫 󠅬 󠅭 󠅮 󠅯 󠅰 󠅱 󠅲 󠅳 󠅴 󠅵 󠅶 󠅷 󠅸 󠅹 󠅺 󠅻 󠅼 󠅽 󠅾 󠅿 󠆀 󠆁 󠆂 󠆃 󠆄 󠆅 󠆆 󠆇 󠆈 󠆉 󠆊 󠆋 󠆌 󠆍 󠆎 󠆏 󠆐 󠆑 󠆒 󠆓 󠆔 󠆕 󠆖 󠆗 󠆘 󠆙 󠆚 󠆛 󠆜 󠆝 󠆞 󠆟 󠆠 󠆡 󠆢 󠆣 󠆤 󠆥 󠆦 󠆧 󠆨 󠆩 󠆪 󠆫 󠆬 󠆭 󠆮 󠆯 󠆰 󠆱 󠆲 󠆳 󠆴 󠆵 󠆶 󠆷 󠆸 󠆹 󠆺 󠆻 󠆼 󠆽 󠆾 󠆿 󠇀 󠇁 󠇂 󠇃 󠇄 󠇅 󠇆 󠇇 󠇈 󠇉 󠇊 󠇋 󠇌 󠇍 󠇎 󠇏 󠇐 󠇑 󠇒 󠇓 󠇔 󠇕 󠇖 󠇗 󠇘 󠇙 󠇚 󠇛 󠇜 󠇝 󠇞 󠇟 󠇠 󠇡 󠇢 󠇣 󠇤 󠇥 󠇦 󠇧 󠇨 󠇩 󠇪 󠇫 󠇬 󠇭 󠇮 󠇯 
</details>

I decided not to go that route since it would have complicated the implementation for unknown benefit. I guess it depends what people are actually using `heck` for. Perhaps that's something to discuss with users before the 0.5 release 😃

**Comment by jplatte** [comment]
None of those cases look particularily interesting. Also, feel free to reach out to users in any way yourself, now or after the RC release.

And thanks! 💚

**Comment by jplatte** [comment]
[v0.5.0-rc.1](https://crates.io/crates/heck/0.5.0-rc.1) is out now.

File: src/kebab.rs [hunk 4]
```diff
@@ -64,7 +66,7 @@ mod tests {
     t!(test6: "SHOUTY_SNAKE_CASE" => "shouty-snake-case");
     t!(test7: "snake_case" => "snake-case");
     t!(test8: "this-contains_ ALLKinds OfWord_Boundaries" => "this-contains-all-kinds-of-word-boundaries");
-    #[cfg(feature = "unicode")]
     t!(test9: "XΣXΣ baﬄe" => "xσxς-baﬄe");
     t!(test10: "XMLHttpRequest" => "xml-http-request");
+    t!(test11: "لِنَذْهَبْ إِلَى السِّيْنَمَا" => "لِنَذْهَبْ-إِلَى-السِّيْنَمَا");
```
Comment (pickfire) [inline src/kebab.rs:71]: Can we add some tests from https://github.com/withoutboats/heck/pull/28/files?

Comment (jplatte) [reply src/kebab.rs:71]: Sure, want to make a new pR?

Comment (pickfire) [reply src/kebab.rs:71]: Okay, let me create a new PR.
